yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(Group,
                              on_delete=models.SET_NULL,
                              blank=True, null=True,
                              related_name='posts'
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст',
                            help_text='Текст нового комментария', blank=False)
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower'
                             )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_sub')
        ]

yatube/posts/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_texts = {'text': 'Текст нового поста', 'group':
                      'Группа, к которой будет относиться пост'}
        labels = {
            'text': 'Текст поста',
            'group': 'Группа'
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {
            'text': 'Текст комментария'
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Comment, Follow
from django.contrib.auth.decorators import login_required
from .forms import CommentForm, PostForm
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from .utils import pages_per_page

POST_PER_PAGE: int = 10


@cache_page(20 * 1, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    context = {
        'page_obj': pages_per_page(request, post_list, POST_PER_PAGE)
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group').all()
    context = {'group': group,
               'page_obj': pages_per_page(request, posts, POST_PER_PAGE)
               }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author').all()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'author': author,
        'page_obj': pages_per_page(request, posts, POST_PER_PAGE),
        'following': following
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments_all = Comment.objects.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments_all
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    cache.clear()
    is_edit = False
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form,
                  'is_edit': is_edit}
                  )


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {'form': form,
                  'is_edit': is_edit, 'post_id': post.pk, 'post': post}
                  )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    followings_posts = Post.objects.filter(
        author__following__user=request.user)
    context = {'page_obj': pages_per_page(
        request, followings_posts, POST_PER_PAGE)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(
            user=request.user,
            author=author).exists() or request.user == author:
        return redirect('posts:follow_index')
    Follow.objects.create(
        user=request.user,
        author=get_object_or_404(User, username=username)
    )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(user=request.user,
                                      author=author)
    if following.exists():
        following.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}           
              </div>
              <div class="card-body">        
                <form method="post" action= {% if is_edit %} {% url 'posts:post_edit' post_id %} {% else %} {% url 'posts:post_create' %} {% endif %} enctype="multipart/form-data">
                  {% csrf_token %}          
                  {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}

{% for post in page_obj %}
<div class="accordion" id="accordionExample">
<ul>
  <li>
    {% if post.author.get_full_name %}
    <a href="{% url 'posts:profile' post.author %}"> Автор: {{ post.author.get_full_name }} {% include 'posts/includes/name.html' %}
    </a>
    {% else %}
    Автор: {{ post.author.get_full_name }} {% include 'posts/includes/name.html' %}
    {% endif %}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }} <br>
  </li>
</ul>
<p>
  <div class="list-group">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}  
    <a href="#" class="list-group-item list-group-item-action list-group-item-info">{{ post.text }}</a>
  </div>     
</p>    
    {% if post.group %}
    <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a> <br>
      <a href="{% url 'posts:group_list' post.group.slug %}">Записи группы: {{post.group}}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description}}</p>
{% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{post.author.get_full_name}}
      </li>
      <li>
        Дата публикации: {{post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %} 
      {{ post.text }}
    </p>       
  </article>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
</div>
{% include 'posts/includes/paginator.html' %}   
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% load cache %}
{% cache 1 list %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
<div class="accordion" id="accordionExample">
<ul>
  <li>
    {% if post.author.get_full_name %}
    <a href="{% url 'posts:profile' post.author %}"> Автор: {{ post.author.get_full_name }} {% include 'posts/includes/name.html' %}
    </a>
    {% else %}
    Автор: {{ post.author.get_full_name }} {% include 'posts/includes/name.html' %}
    {% endif %}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }} <br>
  </li>
</ul>
<p>
  <div class="list-group">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}  
    <a href="#" class="list-group-item list-group-item-action list-group-item-info">{{ post.text }}</a>
  </div>     
</p>    
    <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a> <br>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">Записи группы: {{post.group}}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endcache %} 
{% endblock %}

    

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}       
             
            <li class="list-group-item">
              Группа: {{post.group}}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
              {% endif %} 
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count }} <span></span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}  
          <p>
            {{post.text}}
          </p>
          {% if request.user == post.author %}
          <a href= "{% url 'posts:post_edit' post.id %}"> 
          <div class="form-group mb-2">
          <button class="btn btn-primary">
              Редактировать
          </button></a>
        </div>
        {% endif %}
        {% include "posts/includes/comments.html" %}
      </article>
      {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %} Профайл пользователя {{author}} {% endblock %}
{% block content %}  
      <div class="container py-5"> 
        <div class="mb-5">       
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if request.user != author %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
       {% else %}
      </div>
        {% for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }} {% include 'posts/includes/name.html' %}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %} 
            {{post.text}}
          </p>
          {% if post.id %} 
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          {% endif %}  
        </article>
        {% if post.group %}       
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group}}</a>      
        {% endif %}
      
        {% if not forloop.last %}<hr>{% endif %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор --> 
        {% endfor %}
    
        {% include 'posts/includes/paginator.html' %} 
    </div>
    {%endif%}
        {% endblock %}